window.NETFLIX_SHOWS = [
  {
    title: "3 Body Problem",
    releaseYear: 2024,
    genres: ["sci-fi", "mystery", "drama"],
    moods: ["mind-bending", "serious"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "medium",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "Big-idea science fiction with scale, suspense, and cliff-hanger energy."
  },
  {
    title: "Arcane",
    releaseYear: 2021,
    genres: ["animation", "action", "fantasy"],
    moods: ["emotional", "intense"],
    category: "animation",
    language: "english",
    episodeLength: "standard",
    commitment: "short",
    tone: "dark",
    intensity: "high",
    maturity: "teen",
    popularity: "prestige",
    pitch: "Stunning animated fantasy with heartbreaking character work and serious action."
  },
  {
    title: "Baby Reindeer",
    releaseYear: 2024,
    genres: ["drama", "thriller"],
    moods: ["tense", "serious"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "short",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "prestige",
    pitch: "A short, unsettling watch if you want something powerful and impossible to shrug off."
  },
  {
    title: "Beef",
    releaseYear: 2023,
    genres: ["drama", "comedy", "thriller"],
    moods: ["witty", "chaotic", "messy"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "short",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "prestige",
    pitch: "A viciously funny feud story that swings between absurd comedy and emotional damage."
  },
  {
    title: "Black Mirror",
    releaseYear: 2011,
    genres: ["sci-fi", "thriller", "anthology"],
    moods: ["mind-bending", "dark"],
    category: "scripted",
    language: "english",
    episodeLength: "standard",
    commitment: "medium",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "Choose this when you want dystopian one-night episodes that leave you talking afterward."
  },
  {
    title: "Blue Eye Samurai",
    releaseYear: 2023,
    genres: ["animation", "action", "drama"],
    moods: ["intense", "stylish"],
    category: "animation",
    language: "english",
    episodeLength: "standard",
    commitment: "short",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "prestige",
    pitch: "A revenge epic with gorgeous visuals and very grown-up action."
  },
  {
    title: "BoJack Horseman",
    releaseYear: 2014,
    genres: ["animation", "comedy", "drama"],
    moods: ["witty", "emotional", "heartfelt"],
    category: "animation",
    language: "english",
    episodeLength: "short",
    commitment: "long",
    tone: "balanced",
    intensity: "medium",
    maturity: "adult",
    popularity: "prestige",
    pitch: "Starts absurd and funny, then turns into one of Netflix’s richest character studies."
  },
  {
    title: "Bridgerton",
    releaseYear: 2020,
    genres: ["romance", "drama", "period"],
    moods: ["swoony", "messy"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "medium",
    tone: "light",
    intensity: "medium",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "High-drama romance with lush costumes, scandal, and easy bingeability."
  },
  {
    title: "Cobra Kai",
    releaseYear: 2018,
    genres: ["action", "comedy", "drama"],
    moods: ["fun", "dumb-fun", "adrenaline"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "long",
    tone: "light",
    intensity: "medium",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "Nostalgic, funny, and way more entertaining than it has any right to be."
  },
  {
    title: "Dark",
    releaseYear: 2017,
    genres: ["sci-fi", "mystery", "drama"],
    moods: ["mind-bending", "twisty", "creepy"],
    category: "scripted",
    language: "non-english",
    episodeLength: "long",
    commitment: "medium",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "prestige",
    pitch: "Dense, brilliant time-travel television for when you want your brain fully occupied."
  },
  {
    title: "Dead to Me",
    releaseYear: 2019,
    genres: ["comedy", "drama", "mystery"],
    moods: ["witty", "emotional", "messy"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "medium",
    tone: "balanced",
    intensity: "medium",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "A darkly funny friendship thriller that moves fast and stays entertaining."
  },
  {
    title: "Drive to Survive",
    releaseYear: 2019,
    genres: ["sports", "docuseries"],
    moods: ["high-stakes", "adrenaline"],
    category: "docuseries",
    language: "english",
    episodeLength: "standard",
    commitment: "long",
    tone: "balanced",
    intensity: "high",
    maturity: "general",
    popularity: "mainstream",
    pitch: "A high-octane documentary binge with rivalry, personalities, and momentum."
  },
  {
    title: "Derry Girls",
    releaseYear: 2018,
    genres: ["comedy", "coming-of-age"],
    moods: ["chaotic", "dumb-fun", "heartfelt"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "short",
    tone: "light",
    intensity: "low",
    maturity: "teen",
    popularity: "cult",
    pitch: "A fast, hilarious comfort watch with enormous charm."
  },
  {
    title: "Emily in Paris",
    releaseYear: 2020,
    genres: ["comedy", "romance"],
    moods: ["dumb-fun", "swoony", "messy"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "medium",
    tone: "light",
    intensity: "low",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "Purely breezy, glossy, low-stakes fun."
  },
  {
    title: "Formula 1: Drive to Survive",
    releaseYear: 2019,
    genres: ["sports", "docuseries"],
    moods: ["high-stakes", "adrenaline"],
    category: "docuseries",
    language: "english",
    episodeLength: "standard",
    commitment: "long",
    tone: "balanced",
    intensity: "high",
    maturity: "general",
    popularity: "mainstream",
    pitch: "The easiest way to get instantly invested in Formula 1 drama."
  },
  {
    title: "Gilmore Girls",
    releaseYear: 2000,
    genres: ["drama", "comedy"],
    moods: ["cozy", "witty", "heartfelt"],
    category: "scripted",
    language: "english",
    episodeLength: "standard",
    commitment: "long",
    tone: "light",
    intensity: "low",
    maturity: "general",
    popularity: "classic",
    pitch: "Verbal comfort food for nights when you want something warm and familiar."
  },
  {
    title: "Heartstopper",
    releaseYear: 2022,
    genres: ["romance", "drama", "coming-of-age"],
    moods: ["sweet", "hopeful", "heartfelt"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "short",
    tone: "light",
    intensity: "low",
    maturity: "teen",
    popularity: "prestige",
    pitch: "An earnest, joyful watch when you want tenderness more than tension."
  },
  {
    title: "Is It Cake?",
    releaseYear: 2022,
    genres: ["competition", "reality", "food"],
    moods: ["dumb-fun", "chaotic", "cozy"],
    category: "reality",
    language: "english",
    episodeLength: "standard",
    commitment: "short",
    tone: "light",
    intensity: "low",
    maturity: "general",
    popularity: "mainstream",
    pitch: "Ridiculous, low-pressure reality TV when you want something easy and social."
  },
  {
    title: "Love on the Spectrum U.S.",
    releaseYear: 2022,
    genres: ["reality", "romance"],
    moods: ["sweet", "heartfelt", "cozy"],
    category: "reality",
    language: "english",
    episodeLength: "standard",
    commitment: "short",
    tone: "light",
    intensity: "low",
    maturity: "general",
    popularity: "prestige",
    pitch: "A warm reality series with real emotional payoff and very little cynicism."
  },
  {
    title: "Lupin",
    releaseYear: 2021,
    genres: ["action", "mystery", "thriller"],
    moods: ["slick", "twisty", "fun"],
    category: "scripted",
    language: "non-english",
    episodeLength: "standard",
    commitment: "medium",
    tone: "balanced",
    intensity: "medium",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "A stylish heist series with charisma and momentum."
  },
  {
    title: "Midnight Mass",
    releaseYear: 2021,
    genres: ["horror", "drama", "mystery"],
    moods: ["creepy", "emotional", "tense"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "short",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "prestige",
    pitch: "Slow-burn supernatural horror if you want something rich, thoughtful, and unsettling."
  },
  {
    title: "Mindhunter",
    releaseYear: 2017,
    genres: ["crime", "thriller", "drama"],
    moods: ["tense", "prestige", "gritty"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "medium",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "prestige",
    pitch: "A meticulous crime thriller for nights when you want something gripping and cerebral."
  },
  {
    title: "Mo",
    releaseYear: 2022,
    genres: ["comedy", "drama"],
    moods: ["witty", "heartfelt", "hopeful"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "short",
    tone: "balanced",
    intensity: "low",
    maturity: "adult",
    popularity: "cult",
    pitch: "Funny, humane, and sneaky-emotional with a very distinct voice."
  },
  {
    title: "Money Heist",
    releaseYear: 2017,
    genres: ["crime", "thriller", "action"],
    moods: ["adrenaline", "twisty", "high-stakes"],
    category: "scripted",
    language: "non-english",
    episodeLength: "long",
    commitment: "long",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "Maximalist heist television with huge emotions and bigger cliff-hangers."
  },
  {
    title: "Narcos",
    releaseYear: 2015,
    genres: ["crime", "drama", "thriller"],
    moods: ["gritty", "tense", "prestige"],
    category: "scripted",
    language: "non-english",
    episodeLength: "long",
    commitment: "long",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "A muscular crime saga with a ton of narrative drive."
  },
  {
    title: "Never Have I Ever",
    releaseYear: 2020,
    genres: ["comedy", "romance", "coming-of-age"],
    moods: ["witty", "sweet", "heartfelt"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "medium",
    tone: "light",
    intensity: "low",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "A charming, joke-dense coming-of-age series with real heart."
  },
  {
    title: "ONE PIECE",
    releaseYear: 2023,
    genres: ["action", "fantasy", "adventure"],
    moods: ["fun", "epic", "hopeful"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "medium",
    tone: "light",
    intensity: "medium",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "A big, earnest adventure that is much more fun than cynical."
  },
  {
    title: "Outer Banks",
    releaseYear: 2020,
    genres: ["action", "drama", "mystery"],
    moods: ["fun", "messy", "adrenaline"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "long",
    tone: "balanced",
    intensity: "medium",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "Treasure-hunt teen drama with strong binge pull."
  },
  {
    title: "Ozark",
    releaseYear: 2017,
    genres: ["crime", "thriller", "drama"],
    moods: ["gritty", "tense", "dark"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "long",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "A dark crime spiral for when you want tension and escalation."
  },
  {
    title: "Physical: 100",
    releaseYear: 2023,
    genres: ["competition", "reality", "sports"],
    moods: ["high-stakes", "chaotic", "adrenaline"],
    category: "reality",
    language: "non-english",
    episodeLength: "standard",
    commitment: "short",
    tone: "balanced",
    intensity: "high",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "A wild athletic competition series with immediate hook value."
  },
  {
    title: "Russian Doll",
    releaseYear: 2019,
    genres: ["comedy", "sci-fi", "drama"],
    moods: ["mind-bending", "witty", "chaotic"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "short",
    tone: "balanced",
    intensity: "medium",
    maturity: "adult",
    popularity: "prestige",
    pitch: "A clever, compact loop story that balances philosophy and punchlines."
  },
  {
    title: "Sex Education",
    releaseYear: 2019,
    genres: ["comedy", "drama", "romance"],
    moods: ["witty", "heartfelt", "raunchy"],
    category: "scripted",
    language: "english",
    episodeLength: "standard",
    commitment: "medium",
    tone: "balanced",
    intensity: "medium",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "Warm, funny, character-first TV with a lot of heart."
  },
  {
    title: "Selling Sunset",
    releaseYear: 2019,
    genres: ["reality", "lifestyle"],
    moods: ["chaotic", "messy", "dumb-fun"],
    category: "reality",
    language: "english",
    episodeLength: "standard",
    commitment: "long",
    tone: "light",
    intensity: "low",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "High-polish reality drama when the group wants something social and unserious."
  },
  {
    title: "Squid Game",
    releaseYear: 2021,
    genres: ["thriller", "drama", "action"],
    moods: ["high-stakes", "gritty", "tense"],
    category: "scripted",
    language: "non-english",
    episodeLength: "long",
    commitment: "short",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "A high-stakes global phenomenon if you want something brutal and addictive."
  },
  {
    title: "Stranger Things",
    releaseYear: 2016,
    genres: ["sci-fi", "horror", "adventure"],
    moods: ["epic", "creepy", "fun"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "long",
    tone: "balanced",
    intensity: "medium",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "An event-level binge with monsters, nostalgia, and a huge ensemble."
  },
  {
    title: "Sweet Magnolias",
    releaseYear: 2020,
    genres: ["drama", "romance"],
    moods: ["cozy", "sweet", "hopeful"],
    category: "scripted",
    language: "english",
    episodeLength: "standard",
    commitment: "long",
    tone: "light",
    intensity: "low",
    maturity: "general",
    popularity: "cult",
    pitch: "A cozy relationship drama for a lower-stress watch."
  },
  {
    title: "Sweet Tooth",
    releaseYear: 2021,
    genres: ["fantasy", "adventure", "drama"],
    moods: ["hopeful", "epic", "sweet"],
    category: "scripted",
    language: "english",
    episodeLength: "standard",
    commitment: "medium",
    tone: "balanced",
    intensity: "medium",
    maturity: "teen",
    popularity: "cult",
    pitch: "A gentler fantasy adventure with emotional pull."
  },
  {
    title: "The Crown",
    releaseYear: 2016,
    genres: ["drama", "history"],
    moods: ["prestige", "emotional", "messy"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "long",
    tone: "balanced",
    intensity: "medium",
    maturity: "general",
    popularity: "prestige",
    pitch: "Polished historical drama when you want excellent craft over pure adrenaline."
  },
  {
    title: "The Diplomat",
    releaseYear: 2023,
    genres: ["drama", "thriller", "political"],
    moods: ["prestige", "tense", "witty"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "short",
    tone: "balanced",
    intensity: "medium",
    maturity: "adult",
    popularity: "prestige",
    pitch: "Sharp grown-up drama with quick dialogue and escalating international pressure."
  },
  {
    title: "The Gentlemen",
    releaseYear: 2024,
    genres: ["crime", "action", "comedy"],
    moods: ["slick", "raunchy", "fun"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "short",
    tone: "balanced",
    intensity: "medium",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "A swaggering crime binge with comic energy and easy momentum."
  },
  {
    title: "The Great British Baking Show",
    releaseYear: 2010,
    genres: ["competition", "reality", "food"],
    moods: ["cozy", "heartfelt", "sweet"],
    category: "reality",
    language: "english",
    episodeLength: "standard",
    commitment: "long",
    tone: "light",
    intensity: "low",
    maturity: "general",
    popularity: "classic",
    pitch: "Peak comfort viewing for when the room wants to relax."
  },
  {
    title: "The Lincoln Lawyer",
    releaseYear: 2022,
    genres: ["drama", "crime", "legal"],
    moods: ["slick", "witty", "tense"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "medium",
    tone: "balanced",
    intensity: "medium",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "A clean, satisfying legal binge that is easy to fall into."
  },
  {
    title: "The Night Agent",
    releaseYear: 2023,
    genres: ["action", "thriller", "drama"],
    moods: ["adrenaline", "slick", "high-stakes"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "medium",
    tone: "balanced",
    intensity: "high",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "A streamlined conspiracy thriller that moves fast and rarely lets up."
  },
  {
    title: "The Queen's Gambit",
    releaseYear: 2020,
    genres: ["drama", "period"],
    moods: ["prestige", "emotional", "witty"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "short",
    tone: "balanced",
    intensity: "medium",
    maturity: "adult",
    popularity: "prestige",
    pitch: "A polished limited series with style, momentum, and a strong central performance."
  },
  {
    title: "The Residence",
    releaseYear: 2025,
    genres: ["mystery", "comedy", "drama"],
    moods: ["witty", "chaotic", "cozy"],
    category: "scripted",
    language: "english",
    episodeLength: "standard",
    commitment: "short",
    tone: "light",
    intensity: "low",
    maturity: "teen",
    popularity: "fresh",
    pitch: "A newer, breezier mystery if you want a fresh pick with personality."
  },
  {
    title: "The Umbrella Academy",
    releaseYear: 2019,
    genres: ["action", "sci-fi", "comedy"],
    moods: ["chaotic", "epic", "fun"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "medium",
    tone: "balanced",
    intensity: "medium",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "Offbeat superhero dysfunction with visual flair and binge momentum."
  },
  {
    title: "Wednesday",
    releaseYear: 2022,
    genres: ["comedy", "fantasy", "mystery"],
    moods: ["deadpan", "stylish"],
    category: "scripted",
    language: "english",
    episodeLength: "standard",
    commitment: "short",
    tone: "balanced",
    intensity: "low",
    maturity: "teen",
    popularity: "mainstream",
    pitch: "A visually fun mystery with a gothic-pop attitude."
  },
  {
    title: "When Life Gives You Tangerines",
    releaseYear: 2025,
    genres: ["drama", "romance"],
    moods: ["emotional", "sweet", "prestige"],
    category: "scripted",
    language: "non-english",
    episodeLength: "long",
    commitment: "short",
    tone: "balanced",
    intensity: "medium",
    maturity: "teen",
    popularity: "prestige",
    pitch: "A newer Korean drama pick when you want emotion and cinematic sweep."
  },
  {
    title: "You",
    releaseYear: 2018,
    genres: ["thriller", "drama", "romance"],
    moods: ["twisty", "gritty", "messy"],
    category: "scripted",
    language: "english",
    episodeLength: "long",
    commitment: "long",
    tone: "dark",
    intensity: "high",
    maturity: "adult",
    popularity: "mainstream",
    pitch: "Messy, addictive thriller television with a strong page-turner rhythm."
  },
  {
    title: "Young Sheldon",
    releaseYear: 2017,
    genres: ["comedy", "family"],
    moods: ["cozy", "dumb-fun", "heartfelt"],
    category: "scripted",
    language: "english",
    episodeLength: "short",
    commitment: "long",
    tone: "light",
    intensity: "low",
    maturity: "general",
    popularity: "classic",
    pitch: "An easy, low-friction sitcom-style pick for relaxed viewing."
  }
];
